language: php

php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5
    - 5.6

env:
    - WP_VERSION=trunk
    - WP_VERSION=tags/3.9
    - WP_VERSION=tags/3.8.3
    - WP_VERSION=tags/3.7.3

before_script:
    # set up WP install
    - WP_CORE_DIR=/tmp/wordpress/
    - mkdir -p $WP_CORE_DIR
    - svn co --ignore-externals https://develop.svn.wordpress.org/$WP_VERSION $WP_CORE_DIR
    - plugin_slug=$(basename $(pwd))
    - plugin_dir=$WP_CORE_DIR/src/wp-content/plugins/$plugin_slug
    - cd ..
    - mv $plugin_slug $plugin_dir
    # set up tests config
    - cd $WP_CORE_DIR
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
    - sed -i "s/yourusernamehere/root/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    # disable WP_DEBUG for PHP 5.5 due to ext/mysqli E_DEPRECATED errors
    - if [[ "$TRAVIS_PHP_VERSION" == 5.5* ]] ; then sed -i "s:define( 'WP_DEBUG://define( 'WP_DEBUG:" wp-tests-config.php; fi;
    # set up database
    - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
    # prepare for running the tests
    - cd $plugin_dir
    - npm install -g grunt-cli
    - npm install

script: grunt travis

notifications:
    email: false

    irc:
        channels:
            - "irc.freenode.net#buddypress-dev"
        template:
            - "Build %{build_number} (%{branch} - %{commit}): %{message} %{build_url}"
